### PR TITLE
Update Nokogiri dependency version

### PR DESCRIPTION
**Pull request by krtschmr**

### CODE REVIEW

**Comment by krtschmr** [comment]
@soundasleep  it's critical since nokogiri now released 1.11 on jan 4th

**Comment by krtschmr** [comment]
RIP open source development

**Comment by rmoehn** [comment]
Long live open source development! Because you can make your own fork and fix the problem.

**Comment by krtschmr** [comment]
> Long live open source development! Because you can make your own fork and fix the problem.

yes. funny that you mentioned that, because this is literally a PR from our fork where we fixed the issue.
but overall, it's sad that gems get abandoned.

**Comment by soundasleep** [comment]
I'd love to take on some help to maintain this project! #22 I just don't do Ruby webdev any more these days.

**Comment by agustin** [comment]
Hi @soundasleep seems that on the #22 @Vasfed is offering to be a maintainer. What do you think?

**Comment by mscrivo** [comment]
Fixed with #17

**Pull request closed without merging**
